version: "3"
services:
  backend:
    image: strapi/strapi
    volumes:
      - ./backend:/srv/app
    ports:
      - "1337:1337"
  
  frontend:
    image: node:16.0.0-stretch
    volumes:
      - .:/app
    environment:
      - API_BASEURL=http://localhost:1337
    working_dir: "/app/frontend"
    command: yarn dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
