version: "3"
services:
  strapi:
    image: strapi/strapi
    volumes:
      - ./strapi:/srv/app
    ports:
      - "1337:1337"

  backend:
    build: ./backend
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  
  frontend:
    build: ./frontend
    volumes:
      - .:/app
    environment:
      - API_BASEURL=http://localhost:1337
    ports:
      - "5173:5173"
    depends_on:
      - strapi
      - backend
